//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JOOTASHOP.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class jootaShopEntities1 : DbContext
    {
        public jootaShopEntities1()
            : base("name=jootaShopEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<cartTable> cartTables { get; set; }
        public virtual DbSet<kidsTable> kidsTables { get; set; }
        public virtual DbSet<loginTable> loginTables { get; set; }
        public virtual DbSet<menTable> menTables { get; set; }
        public virtual DbSet<womenTable> womenTables { get; set; }
    }
}
