//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JOOTASHOP.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.Web;

    public partial class productTable
    {
       public static List<string> catTempLint { get; set; }
        public int ProductID { get; set; }
        public string name { get; set; }
        public Nullable<int> catagoryID { get; set; }
        [DisplayName("Upload File")]
        public string imagePath { get; set; }
        public Nullable<int> price { get; set; }
        public Nullable<int> quantity { get; set; }

        public string catagoryName { get; set; }
        public HttpPostedFileBase ImageFile { get; set; }
    }
}
