//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JOOTASHOP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class productAddedBy
    {
        public Nullable<int> productID { get; set; }
        public Nullable<int> catagoryID { get; set; }
        public Nullable<int> AdminID { get; set; }
        public Nullable<System.DateTime> AdditionDate { get; set; }
        public Nullable<System.TimeSpan> AdditionTime { get; set; }
        public int ID { get; set; }
    
        public virtual AdminData AdminData { get; set; }
        public virtual catagoryTable catagoryTable { get; set; }
        public virtual productTable productTable { get; set; }
        public virtual productTable productTable1 { get; set; }
    }
}
